### ISSUE TITLE
Crash if a test reverts

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/medusa#123]
medusa from `main` (8d1519ba19a14c3fdd8a5e314cdbd4762eb1f54f) seems to crash if a test reverts:

```solidity
contract Test {
  function fuzz_revert_always() public returns (bool){
    revert();
  }
}
```

To reproduce the crash:

```
$ medusa fuzz --target crash.sol
...
fuzz: elapsed: 0s, call: 0 (0/sec), seq/s: 0, resets/s: 0, cov: 0
Creating 10 workers ...

Fuzzer stopped, test results follow below ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaf2a74]

goroutine 1 [running]:
github.com/crytic/medusa/fuzzing/executiontracer.(*ExecutionTrace).String(0xc0006b4040?)
	/home/g/Code/medusa/fuzzing/executiontracer/execution_trace.go:277 +0x14
github.com/crytic/medusa/fuzzing.(*PropertyTestCase).Message(0xc0003bd790)
	/home/g/Code/medusa/fuzzing/test_case_property.go:49 +0xbf
github.com/crytic/medusa/fuzzing.(*Fuzzer).printExitingResults(0xc0000cb440)
	/home/g/Code/medusa/fuzzing/fuzzer.go:697 +0x333
github.com/crytic/medusa/fuzzing.(*Fuzzer).Start(0xc0000cb440)
	/home/g/Code/medusa/fuzzing/fuzzer.go:597 +0x55a
github.com/crytic/medusa/cmd.cmdRunFuzz(0x13b26e0?, {0xc0000ccf80?, 0x2?, 0x2?})
	/home/g/Code/medusa/cmd/fuzz.go:125 +0x397
github.com/spf13/cobra.(*Command).execute(0x13b26e0, {0xc0000ccf60, 0x2, 0x2})
	/home/g/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x13b2ca0)
	/home/g/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/g/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/crytic/medusa/cmd.Execute(...)
	/home/g/Code/medusa/cmd/root.go:21
main.main()
	/home/g/Code/medusa/main.go:11 +0x33
```

**Comment by anishnaik** [comment]
Thanks @ggrieco-tob, will debug this in a little bit
