### ISSUE TITLE
Crash when using an incomplete config file

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/medusa#172]
Using an incomplete json file for config results in a crash. For instance:

```json
{
	"fuzzing": {
		"workers": 10
	}
}
```

will crash medusa, despite the json is well formed:

```
Reading configuration file: medusa-config.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb4fed3]

goroutine 1 [running]:
github.com/crytic/medusa/compilation.(*CompilationConfig).GetPlatformConfig(0x0)
	/home/g/Code/medusa/compilation/compilation_config.go:74 +0x33
github.com/crytic/medusa/compilation.(*CompilationConfig).SetTarget(0xc00013cb00?, {0x7fffebfeb33d, 0x1})
	/home/g/Code/medusa/compilation/compilation_config.go:109 +0x2c
github.com/crytic/medusa/cmd.updateProjectConfigWithFuzzFlags(0x7fffebfeb378?, 0xc00013d200)
	/home/g/Code/medusa/cmd/fuzz_flags.go:82 +0x85
github.com/crytic/medusa/cmd.cmdRunFuzz(0x13f8000?, {0xc000129320?, 0x6?, 0x6?})
	/home/g/Code/medusa/cmd/fuzz.go:117 +0x248
github.com/spf13/cobra.(*Command).execute(0x13f8000, {0xc000129260, 0x6, 0x6})
	/home/g/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x13f85c0)
	/home/g/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/g/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/crytic/medusa/cmd.Execute(...)
	/home/g/Code/medusa/cmd/root.go:21
main.main()
	/home/g/Code/medusa/main.go:11 +0x33
```

In this case, the user that the config file will be used to override the default config, without needing to specify all the fields. This can be an usability issue since in our documentation, we want to specify a _short_ config file to override certain values instead of a full file.

**Comment by Xenomega** [comment]
Closed with #187
