### ISSUE TITLE
bug: panic: index out of range 

### ISSUE THREAD

**Issue by tuturu-tech** [crytic/medusa#231]
When trying to run Medusa (dev/no-multi-abi) on Primitive Portfolio:

```
panic: runtime error: index out of range [5059] with length 5059

goroutine 10 [running]:
github.com/crytic/medusa/fuzzing/coverage.(*CoverageMapBytecodeData).update(...)
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/coverage/coverage_maps.go:351
github.com/crytic/medusa/fuzzing/coverage.(*ContractCoverageMap).update(0x102c14e20?, 0x1400d55c3c0?)
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/coverage/coverage_maps.go:274 +0x1fc
github.com/crytic/medusa/fuzzing/coverage.(*CoverageMaps).Update(0x1400d4f5360, 0x1401735ac00?)
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/coverage/coverage_maps.go:153 +0x320
github.com/crytic/medusa/fuzzing/corpus.(*Corpus).CheckSequenceCoverageAndUpdate(0x14002522000, {0x14011734e00?, 0x1e, 0x20}, 0x10?, 0x40?)
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/corpus/corpus.go:395 +0xe4
github.com/crytic/medusa/fuzzing.(*FuzzerWorker).testShrunkenCallSequence.func3({0x14011734e00, 0x1e, 0x20})
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/fuzzer_worker.go:355 +0x5c
github.com/crytic/medusa/fuzzing/calls.ExecuteCallSequenceIteratively(0x1400f558640, 0x1400ee47c78, 0x1400ee47c50)
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/calls/call_sequence_execution.go:120 +0x1e8
github.com/crytic/medusa/fuzzing.(*FuzzerWorker).testShrunkenCallSequence(0x1400e846000, {0x140114d23c0, 0x25, 0x26}, {0x140117f0198?, 0x140117f01b0?, 0xe8?})
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/fuzzer_worker.go:369 +0xcc
github.com/crytic/medusa/fuzzing.(*FuzzerWorker).shrinkCallSequence(0x1400e846000, {0x14010253e00?, 0x1400e846000?, 0x1400f558640?}, {0x140117f0198?, 0x140117f01b0?, 0x0?})
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/fuzzer_worker.go:414 +0x19c
github.com/crytic/medusa/fuzzing.(*FuzzerWorker).run(0x1400e846000, 0x102d1a640?)
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/fuzzer_worker.go:576 +0x3c8
github.com/crytic/medusa/fuzzing.(*Fuzzer).spawnWorkersLoop.func1({0x0?, 0x14010a2e000?})
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/fuzzer.go:547 +0x198
created by github.com/crytic/medusa/fuzzing.(*Fuzzer).spawnWorkersLoop
        /Users/elvisskozdopolj/Documents/GitHub/medusa/fuzzing/fuzzer.go:530 +0x288
```

**Comment by Xenomega** [comment]
Closed per #216
